workflow now check image can be build

diff --git a/.github/workflows/clang-format.yml b/.github/workflows/clang-format.yml
--- a/.github/workflows/clang-format.yml
+++ b/.github/workflows/clang-format.yml
@@ -1,5 +1,5 @@
 name: Clang Format Checker
-on: [push]
+on: [ push ]
 jobs:
   clang-format-checking:
     runs-on: ubuntu-latest
@@ -12,16 +12,16 @@ jobs:
       - uses: RafikFarhad/clang-format-github-action@v3
         with:
           sources: "src/**/*.hpp,src/**/*.cpp,test/**/*.cpp"
-#      - uses: cpp-linter/cpp-linter-action@v2
-#        id: linter
-#        with:
-#          style: 'file'  # Use .clang-format config file
-#          tidy-checks: '.clang-tidy' # Use .clang-tidy config file
-#           only 'update' a single comment in a pull request thread.
-#          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
-#      - name: Fail fast?!
-#        if: steps.linter.outputs.checks-failed > 0
-#        run: exit 1
+      #      - uses: cpp-linter/cpp-linter-action@v2
+      #        id: linter
+      #        with:
+      #          style: 'file'  # Use .clang-format config file
+      #          tidy-checks: '.clang-tidy' # Use .clang-tidy config file
+      #           only 'update' a single comment in a pull request thread.
+      #          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
+      #      - name: Fail fast?!
+      #        if: steps.linter.outputs.checks-failed > 0
+      #        run: exit 1
       - name: Restore cached build
         uses: actions/cache/restore@v4
         with:
@@ -30,6 +30,9 @@ jobs:
 
       - name: Run unit tests
         run: make test
+
+      - name: Build image
+        run: make iso
 
       - name: Save cached build
         uses: actions/cache/save@v4
